name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create Isolated network
        run: docker network create --driver bridge isolated

      - name: Deploy AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: docker run --network=isolated -p 80:80 --name docker-apache -t -d my-php-site:latest

      - name: Get AUT URL
        run: |
          URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: Check AUT Url
        run: curl ${{ env.URL }}

      - name: Deploy Selenium
        run: |
          docker pull selenium/standalone-firefox
          docker run -d \
            --network=isolated \
            -p 4444:4444 \
            -p 7900:7900 \
            --name selenium \
            selenium/standalone-firefox

      - name: Wait until Selenium Ready
        run: bash wait.sh

      - name: Check the Hub
        run: curl http://localhost:4444/ui

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Test
        run: |
          python tests/hello_example.py


      - name: stop docker
        run: docker stop docker-apache