name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create Docker Network
        run: docker network create isolated

      - name: Build AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: |
          docker run -d \
            --name docker-apache \
            --network isolated \
            -p 80:80 \
            my-php-site:latest

      - name: Check AUT
        run: |
          sleep 5
          curl http://localhost

      ###############################################################

      - name: Deploy Selenium
        run: |
          docker run -d \
            --name firefox-standalone \
            --network isolated \
            --shm-size=2g \
            -p 4444:4444 \
            -p 7900:7900 \
            selenium/standalone-firefox:4.18.1

      ###############################################################

      - name: Wait Selenium Ready
        run: |
          echo "Waiting Selenium..."

          timeout 120 bash -c '
          until curl -s http://localhost:4444/status | grep -q "\"ready\":true"
          do
            sleep 2
            echo "Still waiting..."
          done
          '

      ###############################################################

      - name: Show Selenium Status
        run: |
          curl http://localhost:4444/status

      ###############################################################

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Selenium
        run: |
          pip install -U pip
          pip install selenium

      ###############################################################

      - name: Run Test
        run: |
          python tests/hello_example.py

      ###############################################################

      - name: Cleanup
        if: always()
        run: |
          docker ps -a
          docker logs firefox-standalone || true
          docker stop firefox-standalone || true
          docker stop docker-apache || true